# Hugo build configuration for Netlify
# (https://gohugo.io/hosting-and-deployment/hosting-on-netlify/#configure-hugo-version-in-netlify)

[build]
  command = "hugo --environment $HUGO_ENV --config config.toml,config/$HUGO_ENV.toml"
  publish = "public"

[build.environment]
  GO_VERSION = "1.24.5"
  HUGO_VERSION = "v0.148.2"
  HUGO_ENV = "production"

[context.production.environment]
  HUGO_ENV = "production"

# Deploy previews (pull requests) context
[context.deploy-preview.environment]
  HUGO_ENV = "development"

# Branch deploys context
[context.branch-deploy.environment]
  HUGO_ENV = "development"

[[plugins]]
package = "netlify-plugin-checklinks"

  [plugins.inputs]
  # An array of glob patterns for pages on your site
  # Recursive traversal will start from these
  entryPoints = [
    "*.html"
  ]

  # Recurse through all the links and asset references on your page, starting
  # at the entrypoints
  recursive = true

  # Checklinks outputs TAP (https://testanything.org/tap-version-13-specification.html)
  # by default. Enabling pretty mode makes the output easier on the eyes.
  pretty = true

  # You can mark some check as skipped, which will block checklinks
  # from ever attempting to execute them.
  # skipPatterns is an array of strings you can match against failing reports
  skipPatterns = []

  # You can mark some check as todo, which will execute the check, but allow failures.
  # todoPatterns is an array of strings you can match against failing reports
  todoPatterns = []

  # Report on all broken links to external pages.
  # Enabling this will make your tests more brittle, since you can't control
  # external pages.
  checkExternal = true

  # Enable to check references to source maps, source map sources etc.
  # Many build tools don't emit working references, so this is disabled by default
  followSourceMaps = false
